name: Tests with Anypoint CLI
on:
  workflow_dispatch:

jobs:
  create_apim_instance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Install Node on the runner
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install anypoint-cli
      run: |
        npm install -g anypoint-cli-v4
    - name: check version
      run: |
        anypoint-cli-v4 --version
